// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var input = "28\n33\n18\n42\n31\n14\n46\n20\n48\n47\n24\n23\n49\n45\n19\n38\n39\n11\n1\n32\n25\n35\n8\n17\n7\n9\n4\n2\n34\n10\n3";

var parsedInput = input.split("\n").map(Caml_format.caml_int_of_string).sort(function (a, b) {
      return a - b | 0;
    });

var intervals = parsedInput.reduce((function (acc, number, index) {
        var next = Belt_Array.get(parsedInput, index + 1 | 0);
        if (next !== undefined) {
          return Belt_Array.concat(acc, [next - number | 0]);
        } else {
          return Belt_Array.concat(acc, [3]);
        }
      }), [Caml_array.get(parsedInput, 0)]);

console.log(intervals);

function countInArray(array, itemToCount) {
  return array.filter(function (item) {
              return item === itemToCount;
            }).length;
}

var nbOne = countInArray(intervals, 1);

var nbThree = countInArray(intervals, 3);

var result = Math.imul(nbOne, nbThree);

console.log(result);

exports.input = input;
exports.parsedInput = parsedInput;
exports.intervals = intervals;
exports.countInArray = countInArray;
exports.nbOne = nbOne;
exports.nbThree = nbThree;
exports.result = result;
/* parsedInput Not a pure module */
